name: test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -ldflags "-X 'main.version=$(git rev-parse --short=10 HEAD)'" ./cmd/...

    - name: store binary
      uses: actions/upload-artifact@v3
      with:
        name: ttlsetd
        path: ttlsetd

    - name: Test
      run: go test -v ./...
